### ISSUE TITLE
AES-GCM option instead of CBC + HMAC?

### ISSUE THREAD

**Issue by kurtbrose** [sqlcipher/sqlcipher#153]
Any chance of support for AES-GCM instead of CBC + HMAC-SHA1?

**Comment by sjlombardo** [comment]
Hi @doublereedkurt thanks for your interest in SQLCipher. The default constructs used by SQLCipher are selected on the basis a several factors. Security is the highest concern, but so too is broad compatibility. SQLCipher currently supports three different underlying crypto providers, OpenSSL, CommonCrypto (e.g. for iOS, Mac OS X), and libtomcrypt. We have found that the AES-256-CBC + HMAC-SHA1 is the very widely supported across the range of crypto providers and platforms, including older versions that are still widely in use today. Is there a concern with the security of AES-256-CBC and HMAC-SHA1, or do you have specific requirements that mandate your project use AES-GCM?

**Comment by doublereedkurt** [comment]
Thanks for the information.  CBC + HMAC-SHA1 is fine security wise.  (Maybe SHA-2 would be nice?)

My understanding is the main security problem with CBC is timing attacks on the padding; which don't apply to file encryption only network protocols.

The use case we are evaluating SQLCipher for is a shared secure cache among worker processes on a host.  So, the database would live in /dev/shm or /tmp and the data would be considered transient.  As a result, there aren't rules that we use an specific algorithms as long as the encryption is reasonably good.

It is very early in the evaluation, but so far it seems like a great fit for this use case.

**Comment by mikelodder7** [comment]
Any chance of upgrading the the HMAC hash to SHA2-256?

**Comment by sjlombardo** [comment]
@mikelodder7 yes, we are looking into increased HMAC hash lengths for future releases. That said, we can't comment on a specific timeframe because the work involved is non-trivial. There are many details involved, including backwards compatibility, database migrations, provider updates, etc. As mentioned above, HMAC-SHA1 is still considered secure for the way that SQLCipher uses it, and it is widely available. That said, if you have an immediate requirement for an alternative, you could potentially use a custom crypto provider to adjust the implementation for your application.

**Comment by sjlombardo** [comment]
With the SQLCipher 4 release HMAC-SHA512 and PBKDF2-HMAC-SHA512 are now the default HMAC and KDF algorithms respectively. It is also possible to use HMAC-SHA256 and PBKDF2-HMAC-SHA256 by using [PRAGMA settings](https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_hmac_algorithm) as well. SHA1 support is still available to support older database formats and data migration scenarios.

Note that AES-GCM is still not supported by SQLCipher since the provider interface and file format do not facilitate management of the GCM authentication tags.
