### ISSUE TITLE
Broken on Android N Developer Preview

### ISSUE THREAD

**Issue by tadfisher** [sqlcipher/sqlcipher#158]
Looks like libsqlcipher is making unauthorized accesses to non-public APIs in the platform native libraries, which is prevented on N. See http://developer.android.com/preview/behavior-changes.html#ndk for details.

```
libsqlcipher_android.so: unauthorized access to 'libutils.so'
libsqlcipher_android.so: unauthorized access to 'libcutils.so
libsqlcipher_android.so: unauthorized access to 'libnativehelper.so'
libsqlcipher_android.so: unauthorized access to 'libandroid_runtime.so'
libsqlcipher_android.so: unauthorized access to 'libbinder.so'
```

**Comment by developernotes** [comment]
Hi @tadfisher 

Thank you for sharing, we are aware of the warnings that are being produced and plan to look into them further.  Take care!

**Comment by sschuberth** [comment]
@developernotes Wouldn't it make sense to leave this issue open until you actually did look at it and have addressed it?

**Comment by sjlombardo** [comment]
@sschuberth Thanks for following up about this. This issue is logged against the incorrect project. The issue is with android-database-sqlcipher, and you'll notice that there is already an open issue there (https://github.com/sqlcipher/android-database-sqlcipher/issues/216). Thus, being that this ticket is both a duplicate and logged against the incorrect project, we'd prefer to leave it closed. 

With regard to your comment, SQLCipher statically links OpenSSL for security reasons, so it does not rely on an OS crypto provider. As a result, the change to BoringSSL at an OS level is a separate issue. There were a number of other changes with N regarding linking to libraries that SQLCipher for Android depends on outside of OpenSSL that come into play here.

**Comment by developernotes** [comment]
@sschuberth 

No, this is the SQLCipher repository, the issues actually exist within the [SQLCipher for Android](https://github.com/sqlcipher/android-database-sqlcipher/) repository.  We already have an active issue reported [there](https://github.com/sqlcipher/android-database-sqlcipher/issues/216) for Android N.  While Android may be deprecating their usage of OpenSSL, SQLCipher for Android has shipped with a static linking of OpenSSL for several years, thus we are not dependent on the availability of OpenSSL being present on an Android device.

**Comment by sschuberth** [comment]
@sjlombardo @developernotes  Thanks both for the prompt clarification. I completely agree about closing this issue then.

**Comment by powder366** [comment]
Please fix.

**Comment by manish-metacube** [comment]
Do we have any update on this?

**Comment by brodybits** [comment]
@manish-metacube AFAIK the original issue was handled and fixed in https://github.com/sqlcipher/android-database-sqlcipher/issues/216 last year.

**Comment by developernotes** [comment]
Hi @manish-metacube 

@brodybits is correct, the issue was addressed with our release last year that supports Android 7.

**Comment by manish-metacube** [comment]
Thanks! @brodybits.
