### ISSUE TITLE
Doesn't cross-compile to Windows

### ISSUE THREAD

**Issue by nurupo** [sqlcipher/sqlcipher#176]
We cross-compile sqlcipher for Windows on a Linux machine and to make it work we have to jump through some hoops, instead of it just working.

~~Here is how we currently make it work.~~

``` sh
REMOVED, SEE BELOW
```
[(old version)](https://web.archive.org/web/20171224151436/https://github.com/sqlcipher/sqlcipher/issues/176).

~~It's Debian 8 system. libopenssl_build_windows_x86-64_static_release.zip is a static openssl, cross-compiled for Windows.~~

~~Would be nice if you could fix the build system for windows cross-compilation to work out of the box or point out if we are doing something wrong.~~

~~SQLCipher version is 3.4.0~~

**EDIT**: [Here is an updated version for 3.4.2](https://github.com/qTox/qTox/blob/9525505bff8719c84b6193174ea5e7ec097c54b8/windows/cross-compile/build.sh#L390-L446). Make sure you copy tabs as tabs and spaces as spaces, without removing any trailing white-space in the patch part, as the patch will likely fail to apply because of that.

**EDIT2**: [Same but for 4.2.0](https://github.com/qTox/qTox/blob/51c5171ca395ca35c934e0357748e512d746f356/windows/cross-compile/build.sh#L389-L447).

**EDIT3**: [For 4.4.0](https://github.com/qTox/qTox/blob/4e4e77b59410f3a12289794a79ae2f9cd8d6766d/windows/cross-compile/build.sh#L389-L427).

**Comment by sagara-** [comment]
There's two issues at work here; one within sqlcipher itself, and one within openssl.

For sqlcipher, the issue arises due to how EXEEXT is used within configure.ac. EXEEXT is set by autoconf itself to the target platform's exe extension. However, in one case (the lemon parser), we actually want the building platform's extension. configure.ac sets BUILD_EXEEXT to EXEEXT unless CYGWIN is set to 'yes', which when cross-compiling on linux with the mingw toolchain will always be set to .exe; there's no way to override this currently. config_BUILD_EXEEXT can be passed when running ./configure but it's only ever used to set CYGWIN=yes.

A simple fix would be allowing to set BUILD_EXEEXT from configure explicitly, and only attempting to set it within configure if the user didn't specify it. Another, slightly more complicated fix would be changing configure.ac to use something like https://www.gnu.org/software/autoconf-archive/ax_cc_for_build.html which can be used to find a compiler on the building machine instead of using AC_CHECK_PROGS, as this seems to set CC_FOR_BUILD and EXEEXT_FOR_BUILD which could then be used as values for BUILD_CC and BUILD_EXEEXT. I haven't tried this myself however, but it seems to be used in a few projects for this purpose.

The other issues is with your openssl build; openssl provides a public, windows-only RAND_screen function, which uses gdi to seed the PRNG with the current screen contents (see crypto/rand/rand_win.c). On all other platforms the function does nothing. One way to remove this dependency is to run Configure with -DOPENSSL_SYS_WIN32_CYGWIN; this is only used in 3 places; for the body of RAND_screen, within e_os.h to include io.h and fnctl.h, and finally in crypto/bio/bss_file.c, where it ends up calling fileno() and setmode() instead of _fileno() and _setmode(). None of these cause issues, as the headers are available in the mingw toolchain, fileno and setmode are still valid functions (MS just considers them deprecated), and RAND_screen isn't used within openssl itself, or within sqlcipher anyways. If you prebuilt versions of openssl, then you still need to add the gdi dependency  to sqlcipher somehow, so maybe something can be exposed to do so in those cases.

So if you remove the gdi32 dependency, you can do a success cross-compile by just adding BUILD_EXEEXT="" above AC_SUBST(BUILD_EXEEXT) in configure.ac, then running autoreconf, as the rest of the build process works fine.

**Comment by polesapart** [comment]
I've built with a patch or two a few months ago, in case anyone is curious, here is the source: https://build.opensuse.org/package/show/home:polesapart:win64/mingw64-x-sqlcipher

**Comment by nurupo** [comment]
@polesapart how do I see your patches? Spent 5 minutes clicking all over the web UI and couldn't figure out how to get the tarballs with your patches in them. Please provide a direct link.

**Comment by polesapart** [comment]
@nurupo  sorry somehow I missed your mention. dm me if you're still looking (hint: there's a download button in the "actions" column - you'd need the debian.tar.xz file, the patches are inside it).

**Comment by nurupo** [comment]
Since I got just reminded of this thread, I have updated the top post for 3.4.1.

**Comment by nurupo** [comment]
@polesapart the download button doesn't download anything, it just redirects me to the same page. Apparently it requires some kind of authentication?

```sh
$ wget https://build.opensuse.org/source/home:polesapart:win64/mingw64-x-sqlcipher/mingw64-x-sqlcipher_3.4.1-1.debian.tar.xz?rev=dc59c34986627472d0ccdc5888580805
--2017-12-24 15:19:14--  https://build.opensuse.org/source/home:polesapart:win64/mingw64-x-sqlcipher/mingw64-x-sqlcipher_3.4.1-1.debian.tar.xz?rev=dc59c34986627472d0ccdc5888580805
Resolving build.opensuse.org (build.opensuse.org)... 195.135.221.133, 2001:67c:2178:8::12
Connecting to build.opensuse.org (build.opensuse.org)|195.135.221.133|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
```

**Comment by polesapart** [comment]
@nurupo  I've uploaded both my openssl & sqlcipher sources to this url: https://polesapart.github.io/

**Comment by sjlombardo** [comment]
Closing, as this ticket hasn't been updated in some time.
