### ISSUE TITLE
net.sqlcipher.database.SQLiteException: error code 5: database is locked

### ISSUE THREAD

**Issue by srinivas3120** [sqlcipher/sqlcipher#183]
Error inserting redacted values> into Medicinemaster
net.sqlcipher.database.SQLiteException: error code 5: database is locked
                                                                     at net.sqlcipher.database.SQLiteStatement.native_execute(Native Method)
                                                                     at net.sqlcipher.database.SQLiteStatement.execute(SQLiteStatement.java:58)
                                                                     at net.sqlcipher.database.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1994)
                                                                     at net.sqlcipher.database.SQLiteDatabase.insert(SQLiteDatabase.java:1850)

SQLCipher version: 3.5.4

i am getting this exception very frequently.
I am using 2 SQLiteOpenHelper instances to create and manage the database connection.  
db_1.db and db_2.db. I have successfully created both the databases.  

**Problem:**
I start inserting into tables of db_1.db and it works. but when i start inserting into tables of db_2.db, i get "error code 5: database is locked" exception. what wrong am i doing ?

1. when do i get "database is locked" exception
2. can i open two databases simultaneously and how to handle it ? (are 2 SQLiteOpenHelper instances enough)

**Comment by developernotes** [comment]
Hi @srinivas3120 

Yes, you can open separate connections to different databases. Are you able to replicate your issue within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?

**Comment by srinivas3120** [comment]
i could not find a way to test my case using test suites available at https://github.com/sqlcipher/sqlcipher-android-tests ?

anyway, what is that am i doing wrong ? why am i getting "database lock" exception.

**Comment by sjlombardo** [comment]
@srinivas3120  -  please see this post in response to your earlier support thread:

https://discuss.zetetic.net/t/database-locked-error-code-5/1763

**Comment by groue** [comment]
@srinivas3120 You do nothing wrong.

But you have to learn that **SQLite locks a database when a connection is writing in it**. When a connection writes, it first acquires a *lock* that it eventually releases when the write has been performed and written to disk. Meanwhile, other connections can't acquire this lock, and get "database is locked" errors.

The error happens when the second connection attempts to write, or attempts to read in the locked database.

To avoid this error between writers, you have to setup a "busy handler". Busy handlers have connections automatically *wait* until the lock is released. Have a thorough read of [Register A Callback To Handle SQLITE_BUSY Errors](https://www.sqlite.org/c3ref/busy_handler.html) and [Set A Busy Timeout](https://www.sqlite.org/c3ref/busy_timeout.html) so that you understand the topic, and look for the java APIs that let you leverage those features.

To avoid this error for readers, and let a connection read in a locked database, you can investigate the [WAL mode](https://www.sqlite.org/wal.html). The WAL mode lets readers read without waiting for the lock to be released. But it does not fit all situations: again I recommend a thorough read of the documentation. And it won't prevent concurrent writers to race: you really need a busy handler for concurrent writers.

Welcome in the funny world of SQLite concurrency!

**Comment by srinivas3120** [comment]
@groue thank you.
what i know is that, sqlite is itself a thread safe! I get this exception when i have two different database open connections. insertion on one database works across threads but, when i try to insert in other database i get this exception.  is there a limit on number of open database connections per application ?

how can i open two databases and how to handle db operations simultaneously ?

**Comment by groue** [comment]
> what i know is that, sqlite is itself a thread safe!

Yes it is, and this is why it returns a nice error instead of corrupting your data when it is used in a way it does not support. Thread safety does not always mean what one wants...

> I get this exception when i have two different database open connections. insertion on one database works across threads but, when i try to insert in other database i get this exception. is there a limit on number of open database connections per application ?

No, there is no limit. Read again my comment, and do your homework.

**Comment by srinivas3120** [comment]
for a side note, without falling into this trap. :P
how can i open two databases and how to handle db operations simultaneously ?

**Comment by developernotes** [comment]
Hi @srinivas3120 

>how can i open two databases and how to handle db operations simultaneously

There are a few different options, depending on what you need to perform. There are various static methods (i.e., `openDatabase`, and `openOrCreateDatabase`) on the `SQLiteDatabase` class, there is the `SQLiteOpenHelper`, and finally you can simply [`ATTACH`](https://www.zetetic.net/sqlcipher/sqlcipher-api/#attach) an additional database to an existing connection.

**Comment by srinivas3120** [comment]
@developernotes and @groue thank you.
