### ISSUE TITLE
library is adding 6mb to apk size

### ISSUE THREAD

**Issue by srinivas3120** [sqlcipher/sqlcipher#184]
Sqlcipher library is adding 6mb to apk size !

For sake of encryption, 6mb is not acceptable for a user. any progard rules to add ? i have added this. no help!
`-keep class net.sqlcipher.** { *; }`
How much of size does sqlcipher library add to apk size ? How can i reduce the size ?

**Comment by developernotes** [comment]
Hi @srinivas3120 

If you need to decrease the size of your apk, you might consider limiting the native platforms your application is including support for. SQLCipher for Android includes support for `armeabi`, `armeabi-v7a`, and `x86`. Since you are not reporting an issue, I will mark this as closed. Please consider asking questions within the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher) in the future.
