### ISSUE TITLE
SQL variable count too low on iOS and macOS

### ISSUE THREAD

**Issue by jcavar** [sqlcipher/sqlcipher#213]
Hi, we encountered issue with low SQL variable count when using it with CoreData:

### Expected Behavior
SQL variable count about the same as iOS and macOS default
### Actual Behavior
SQL variable count 999

See:
https://github.com/project-imas/encrypted-core-data/issues/274

I think what we need to do here is just to update sqlcipher podspec and change this number in `GCC_PREPROCESSOR_DEFINITIONS`

The exact number should be 500000 I guess because that is iOS and macOS default.

**Comment by sjlombardo** [comment]
@jcavar 500000 seems excessive, even if it is the default for standard SQLite on iOS and macOS. Setting the the max variable number that high could inadvertently cause substantial memory utilization depending on the SQL used. 

Can you give some practical examples of where you are using that many bound parameters?

**Comment by jcavar** [comment]
We are not using that many but 999 is limitation for us. We are using CoreData request in form "identifier IN %@, array". And 999 objects is relatively small number. 

If you check this out 
http://sqlite.1065341.n5.nabble.com/SQLITE-MAX-VARIABLE-NUMBER-td43457.html
500000 is 36mb which is for these platform generally fine. Actual data returned by the query like this would probably be much bigger. 

I understand that sqlcipher is used on many platforms and it makes sense to keep reasonable default, but we can change it in Podfile only so it will affect its users only. 

Another argument to increase it is that this is upper bound and actual limit can be changed dynamically, which is not possible other way around. 

I would assume that there are ways around this but we are not in control of generated query so we are kind of stuck.

**Comment by sjlombardo** [comment]
@jcavar If we were to make a change to the default, it would have to be coordinated across all of the supported SQLCipher packages and configurations. We generally try to avoid making one of changes to specific distributions because it breaks expectations for standardized behavior, introduces functional inconsistencies,  and generally makes support more difficult. 

You mentioned that you are not using the upper limit of 500000. Out of curiosity, how many are you actually using in practice in the CoreData example you referred to?

**Comment by jcavar** [comment]
I mean, we are using 999 but we have to fetch multiple times to workaround this. Somewhere between 2000 and 3000 is what we would probably use.

Regarding default changes, since only reason to limit this is memory usage (right?), I think it makes sense that actual number differs between platforms depending on available memory.

**Comment by sjlombardo** [comment]
@jcavar thanks for the additional context for your usage scenario. While I appreciate your point of view, there is really no way to tell at compile time for a library how much available memory any given platform will have, or how the library will be used by an application (e.g. whether it will process user-provided SQL). We try to use sensible defaults that will be low risk and work on the broadest range of configurations unless there is a very compelling reason not to do so. We'll discuss this further and consider increasing this default limit for a future release.

**Comment by jcavar** [comment]
@sjlombardo thanks :)

**Comment by rnewman** [comment]
N.B., applications can lower the limit at runtime to whatever they wish, allowing them to limit memory consumption for large queries (by refusing to run them). Applications cannot raise the limit to higher than the compile-time limit.

That's a pretty good reason to match the OS limit rather than SQLite's very conservative default.

**Comment by developernotes** [comment]
Hi @jcavar, @rnewman 

We plan to increase `SQLITE_MAX_VARIABLE_NUMBER` with the next release of SQLCipher. Thanks!

**Comment by mig5** [comment]
It seems to still be 999..

**Comment by developernotes** [comment]
Hi @mig5 

Where are getting SQLCipher from? Both our Commercial edition and CocoaPods distribution utilize `99999`.

**Comment by mig5** [comment]
@developernotes I'm getting SQLcipher straight from github, (master branch), and compiling on Linux.

https://github.com/sqlcipher/sqlcipher/blob/master/src/sqliteLimit.h#L136

I've re-compiled with CFLAGS to include `-DSQLITE_MAX_VARIABLE_NUMBER=250000` (to match Debian, Ubuntu's SQLite variable) and it works.

**Comment by developernotes** [comment]
Hi @mig5 

Sorry, I was not clear [here](https://github.com/sqlcipher/sqlcipher/issues/213#issuecomment-333671515). When I said that we would change the default, that applies to the binary packages that we provide directly (which we did). We try to minimize the changes we introduce where SQLite and SQLCipher would differ. Since you are able to provide an override via `-DSQLITE_MAX_VARIABLE_NUMBER`, that would be our recommendation (that is what we do as well).

**Comment by mig5** [comment]
@developernotes no worries, thanks for the clarification!
