### ISSUE TITLE
ios11 "file is encrypted or is not a database" after updated

### ISSUE THREAD

**Issue by oremag14jf** [sqlcipher/sqlcipher#234]
### Expected Behavior
Access the encrypted database successfully.

### Actual Behavior
"file is encrypted or is not a database"

### Steps to Reproduce
My iOS project included SQLCipher cloned SQLCipher directly into the same folder, as indicated in https://www.zetetic.net/sqlcipher/ios-tutorial/ . This works fine, but when I migrated to ios11, my project not works. 
It appears error "sqlite3_key is invalid in C99". I reported this problem here: https://github.com/sqlcipher/sqlcipher/issues/225
I've change SQLCipher included by Pods, and the error "sqlite3_key is invalid in C99" disappear. But now, when I run my app, it show me the error "file is encrypted or is not a database".

SQLCipher version:
3.4.1

**Comment by billymeltdown** [comment]
Hi there,

This is a problem with the build configuration in use, not a bug in SQLCipher, though the tutorial you have referenced could use an update. I think the reason you are experiencing this problem is because in the Xcode 9 **beta** (which you're using to build for iOS 11 **beta**) it seems we need to ensure that the `sqlite3.h` generated when building SQLCipher is included in the project's Navigator listing, it's no longer enough to simply update Header Search Paths to include the path to your `sqlite3.h`. Note that you wouldn't select any targets to add it to directly when adding the file to the navigator listing.

<img width="348" alt="screen shot 2017-08-08 at 9 08 42 am" src="https://user-images.githubusercontent.com/2420/29073342-4e4e64b2-7c19-11e7-9015-2f78f9a4ea2a.png" />

<img width="258" alt="screen shot 2017-08-08 at 9 09 49 am" src="https://user-images.githubusercontent.com/2420/29073356-5c6f57fe-7c19-11e7-9e3d-11c8e51e2031.png" />

That's likely the issue, but it could be something else (e.g. an incorrect search path, missing `-DSQLITE_HAS_CODEC` cflag, etc). Either way to continue this discussion please open up a new topic on our discussion forum as we use GitHub's Issues interface for tracking bugs:

https://discuss.zetetic.net/c/sqlcipher

In the meantime we'll get that tutorial link updated.

**Comment by oremag14jf** [comment]
In my included project SQLCipher, not appear sqlite3.h. I have sqlite3.c.
 
![captura de pantalla 2017-08-09 a las 12 11 23](https://user-images.githubusercontent.com/12425280/29116725-13b18c92-7cfc-11e7-9c9e-fbe56760b957.png)

**Comment by sjlombardo** [comment]
@oremag14jf I don't believe we ever got a full xcode build log from you. Can you please post the output of ls -R from the top level of your project along with the full Xcode build log so we can take a look. Please make sure it is the full Xcode build log (i.e. not just the errors) so that we can see the raw parameters passed to the command line compiler to compare the include folders and defines against the project structure. Also, posting to a Github Gist would be best because the log will be very long. I guarantee this is a configuration problem. If this is just happening for x64, you might have an architecture specific override that is causing the problem.

**Comment by oremag14jf** [comment]
Hi @sjlombardo.

This is ouput of ls -R:
https://gist.github.com/oremag14jf/46deb3b9d31a4850b5a9e7f9f417eeab

Here is the full Xcode build: https://gist.github.com/oremag14jf/174ed708449453aaba9fca733d653152

**Comment by sjlombardo** [comment]
Hello @oremag14jf  I looked at the log. It doesn't look like you have the sqlcipher source folder in the header search paths. Per the instructions, navigate to your Project settings (make sure you don't select the application target level). Select the Build Settings pane. In the search field, type in "Header Search Paths". Double-click on the field under the target column and add the following path: $(PROJECT_DIR)/<path to sqlcipher src directory>

**Comment by oremag14jf** [comment]
Hello @sjlombardo 
Sorry, but I modified several things and did not set the correct path. I have put the indicated path and the same error still appears.

Here is the full Xcode build:
https://gist.github.com/oremag14jf/022687a61a076073c72df4754bde780a

**Comment by sjlombardo** [comment]
@oremag14jf it still does not look like you have defined that path in the Header Search Paths for your top level project. It looks like you may have defined it on the SQLCipher sub-project, but not for your own code. you can see in the compile line immediately before the error that the path to the sqlcipher directory is not being included via `-I` flags. Please add the path to your top level project or target definition.
