### ISSUE TITLE
ar 

### ISSUE THREAD

**Issue by kajol9405** [sqlcipher/sqlcipher#236]
### Steps to Reproduce

SQLCipher version:

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by developernotes** [comment]
Hi @kajol9405 

We will be closing this ticket because there was no information included. If you have an issue to report, please repost it including detailed information. If you have a question about SQLCipher, please feel free to post to our SQLCipher [discuss](https://discuss.zetetic.net/c/sqlcipher) site.
