### ISSUE TITLE
Fix xCode warnings

### ISSUE THREAD

**Issue by christophhagen** [sqlcipher/sqlcipher#237]
### Expected Behavior

No build warnings

### Actual Behavior

Around 95 warnings 'Ambiguous expansion of macro ...'

### Steps to Reproduce
- Use sqlcipher through cocoapods in other Xcode project
- Build project
- Several warnings occur: 'Ambiguous expansion of macro MAX'

### Fix

Replace macros MIN and MAX with something unique, i.e. MMIN/MMAX

SQLCipher version: 3.4.1

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by sjlombardo** [comment]
Hello @christophhagen thanks for getting in touch about this. These definitions are actually part of the SQLite upstream code base. We have a strong policy not to divert or change the upstream code more than necessary, as it makes merging and upgrading difficult and risky, and as such, we would not fix these. However, because these warnings also affect stock SQLite, and have been discussed on the users mailing list before, it is our hope that they may be resolved in future updates to SQLite, which would then be brought into the SQLCipher project. 

In the mean time, if the warnings are causing a major issue, you could pass `-Wno-ambiguous-macro` in the compiler flags to silence the warnings, or remove the definitions from the source code locally.
