### ISSUE TITLE
error while installing SQLCipher via cocoaPods

### ISSUE THREAD

**Issue by Yuop** [sqlcipher/sqlcipher#252]
### Actual Behavior
have this error while installing pod to my project 
`/usr/local/bin/bash: ./configure: /bin/sh^M: bad interpreter: No such file or directory`

SQLCipher version: 3.4.1

Have any ideas what's going wrong?

**Comment by developernotes** [comment]
Hi @Yuop 

We utilize Github Issues for reporting reproducible defects with the SQLCipher source. For project configuration questions, we would recommend asking over in the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher). It appears you may have DOS line endings due to the `^M` in the error message, you might investigate that first. Feel free to post any follow-ups on discuss. Thanks!
