### ISSUE TITLE
iOS apps are terminated every time they enter the background if they share an encrypted database with an app extension.

### ISSUE THREAD

**Issue by charlesmchen** [sqlcipher/sqlcipher#255]
I've created a minimal demo app that demonstrates the issue using a trivial SQLCipher database.  It's README.md contains detailed discussion and steps to repro.

https://github.com/WhisperSystems/SQLCipherVsSharedData

### Summary

iOS apps can't share an encrypted database with app extensions (e.g. share extensions) without being terminated every time they are suspended.  

iOS won't let suspended apps retain a file lock on apps in the "shared data container" used to share files between iOS apps & their app extensions.

This seems to affect all versions of iOS and all device models.

This issue can be reproduced with very simple SQLite/SQLCipher code, but there is a little bit of complexity around using a "shared data container" on an iOS device.  This demo app takes care of that.

### Discussion

* To share a database (or any other file) between an iOS app and iOS app extension (e.g. a share extension), the file must reside in the "shared data container", a special area of the file system accessible by all apps in an "app group".
  * See: https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html
* iOS terminates apps almost immediately if they retain a file lock on any file in the shared data container while being suspended.
  * See Apple's documentation https://developer.apple.com/library/content/technotes/tn2151/_index.html
`
The exception code 0xdead10cc indicates that an application has been terminated by the OS because it held on to a file lock or sqlite database lock during suspension. If your application is performing operations on a locked file or sqlite database at suspension time, it must request additional background execution time to complete those operations and relinquish the lock before suspending.
`
  * iOS only terminates apps for this reason when app transition from the `background` to `suspended` states.  iOS main apps can delay being suspended by creating a "background task", but this only defers the issue briefly as there are strict limits on the duration of "background tasks".
  * `0xdead10cc` terminations don't occur in the simulator and won't occur on devices if the debugger is attached.
  * These `0xdead10cc` terminations usually don't yield crash logs on the device, but always show up in the device console logs.
* SQLCipher databases appear to retain a file lock on the database file at all times in some configurations, even when the database is not being accessed.
  * This demo app demonstrates this behavior using an empty database with encryption enabled and  `journal_mode = WAL`.
  * There may be other configurations that also demonstrate this issue.
  * SQLCipher databases without encryption enabled _DO NOT_ exhibit this issue.
* iOS apps which keep an encrypted SQLCipher database open at all times are terminated every time it is sent to the background, even if they are not doing any explicit database access.
* iOS apps frequently enter the background as users switch between apps.  Being terminated in the background means that users must wait for app to relaunch and lose any transient state, e.g. view state.

### Steps to Reproduce

This issue doesn't reproduce in a simulator, so we're going to need to run on an actual iOS device (not a simulator), which means we'll need to use valid "app ids" and "app group ids".

The demo app:

* Creates a _new_ database (located in an iOS shared data container) using `sqlite3_open_v2()`  and `SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE | SQLITE_OPEN_NOMUTEX | SQLITE_OPEN_PRIVATECACHE`.
* Encrypts that database using `sqlite3_key()`.
* Enables write-ahead logging by executing `PRAGMA journal_mode = WAL` with  `sqlite3_exec()`.
* Creates a table by executing `CREATE TABLE groups ( group_id integer PRIMARY KEY )` with  `sqlite3_exec()`.

Every time you run the app on a physical device (without the debugger attached), then send it to background, it will be terminated immediately by iOS.  This can be observed in the console.

Note: iOS may immediately relaunch the app in the background a few times, but it will re-terminate it each time.

### How to use the demo app:

Note: the README.md of the demo app contains illustrations, etc. https://github.com/WhisperSystems/SQLCipherVsSharedData

* Make sure you have an active iOS Developer Account and an iOS device running iOS 9 or later.
* Download the demo app here: 
  * https://github.com/WhisperSystems/SQLCipherVsSharedData
* You need to create your own app id and app group, since you'll need to code sign the app using your developer account.
  * Go to Apple's iOS developer center
  * https://developer.apple.com/account/ios/identifier
  * Create a new app group.
     * The description doesn't matter.
     * Select an "app group id" like "group.com.yourcompany.something".
  * Create a new application id.
    * The description doesn't matter.
    * Select an "app id" like "com.yourcompany.something".
    * Enable App Groups & configure App Groups using the "app group id" you created above.
* Download this demo project and open it in a recent XCode (e.g. 9.x).
* Change App Id
  * Select the Project Navigator (left tab in left pane).
  * Select SQLCipherVsSharedData workspace.
  * Select SQLCipherVsSharedData target in left pane of editor.
  * Select General tab.
  * Change the bundle id to match the "app id" you created above.
* Change Group Id
  * Select Capabilities tab.
  * Make sure the "app groups" capability is enabled and _only_ the "app group id" you selected above is active.
* Code Changes
  * Open AppDelegate.m.
  * Modify kApplicationGroupId constant to reflect the "app group id" you created above.
* Reproducing the Termination
  * Run the app on your device - _NOT_ the simulator.
  * iOS doesn't terminate apps with 0xdead10cc in the simulator.
  * If you have signing problems, contact me at matthew@whispersystems.org.
  * Kill/stop the app in order to end the debugging session.
  * iOS doesn't terminate apps with 0xdead10cc if the debugger is attached.
  * On your attached Mac, open the Console app and select your iOS device in the left sidebar.
  * Launch the app.
  * Send the app to the background.
  * In Console (on your mac), you should see an entry like this:
  
```
  default    16:08:57.000000 -0500    SpringBoard     Forcing crash report of <FBApplicationProcess: 0x1394b57d0; SQLCipherVsShar; pid: 4146> (reason: 4, description: <FBApplicationProcess: 0x1394b57d0; SQLCipherVsShar; pid: 4146> was suspended with locked system files:
  /var/mobile/Containers/Shared/AppGroup/FCC1D74E-36AD-439C-B2AD-9E6D5B407DED/Database-Filename-51898.sqlite)

```

SQLCipher version:

3.4.1

**Comment by sjlombardo** [comment]
@charlesmchen Thank you for the very detailed report. We'll look into reproducing this and try to track down what is happening here.

**Comment by sjlombardo** [comment]
Hello @charlesmchen - Just a quick update, we've been able to reliably reproduce the problem with forced application termination within the sample application. We're looking into the cause now.

**Comment by charlesmchen** [comment]
@sjlombardo Fantastic, Stephen.  Thank you so much for taking a look.

**Comment by sjlombardo** [comment]
@charlesmchen This is an interesting issue. After ruling out a number of potential issues, I decided to narrow the scope if inquiry by implementing a minimal pass-through codec in the sample project's amalgamation (i.e. to replace SQLCipher entirely). Even after removing practically all of the SQLCipher code I was still able to reproduce the same issue. This leads me to suspect that there is some issue in the base SQLite code that is triggered whenever a codec is attached to the pager and WAL journal mode is enabled. 

We will continue to look into this to see if we can track down the root cause. Depending on what we find this may require adjustment in SQLite upstream.

In the mean time, may I ask if WAL is a strict requirement for your implementation? If not, the standard journal mode does not exhibit this behavior, and may be a good workaround. By way of example, we have successfully deployed SQLCipher with the standard journal mode in an iOS application with a bundled extension using a shared data container, and have not had any issues.

**Comment by charlesmchen** [comment]
@sjlombardo Great.

> This leads me to suspect that there is some issue in the base SQLite code that is triggered whenever a codec is attached to the pager and WAL journal mode is enabled.

That seems reasonable.

> In the mean time, may I ask if WAL is a strict requirement for your implementation?

Yup, we're using YapDatabase which requires WAL.

> Depending on what we find this may require adjustment in SQLite upstream.

Great.  It might be helpful to create a similar minimal repro app that: a) repros the issue by activating WAL with a pass-through codec and b) doesn't contain any SQLCipher code.  I'm not sure if you'd like to open an issue with Sqlite; I'd be very happy to help as well, although my knowledge of Sqlite isn't deep.

**Comment by sjlombardo** [comment]
@charlesmchen we're going to continue to look into this a bit further to see if we can narrow down the cause. I'll be back in touch when I have a bit more information.

**Comment by sjlombardo** [comment]
Hello @charlesmchen. I believe we've determined the root cause for this issue. It's does not appear to be a bug in SQLite or SQLCipher. Instead it appears that iOS is actually examining the database file to determine whether it is a SQLite database in WAL mode, and then extending special locking privledges if it is, allowing the process to maintain a lock on the main database while it is backgrounded.

Unfortunately in the case of a SQLCipher database the file is encrypted so the header (specifically the "SQLite Format 3\0" and the Database read/write version numbers in offsets bytes 0 - 19 that indicate WAL mode is being used) contain apparently random data when examined directly. This seems to be causing iOS to identify the file as a non-SQLite database, and thus enforce more stringent locking rules. 

This behavior does not appear to be well documented, however I did locate this [Apple technical note](https://developer.apple.com/library/content/technotes/tn2408/_index.html) that implies SQLite WAL databases are treated "specially" in the context of a shared container.

The reason that this doesn't affect non-encrypted databases is that the header is readable. It does not affect encrypted databases using the standard journal mode because all locks are released when the database is not in use, unlike WAL mode where a lock is maintained even when a transaction is not active. Only the combination of a an encrypted database and WAL mode will trigger the issue when using a SQLCipher build. That said, it is possible to reproduce this issue with a non-encrypted database simply by changing the SQLITE_FILE_HEADER define in a standard SQLite amalgamation to something other than "SQLite format 3". Changing a single byte there, e.g. f to F, will cause iOS to misidentify the file and then kill the process immediately if WAL mode is used. 

The bad news is that this makes resolution particularly difficult because there isn't a simple bug fix we can put in place. A few potential options follow, though none of them are particularly desireable.

1. Consult with the YapDatabase team to determine whether it is possible to disable WAL mode and use the standard journal mode instead. This would affect the concurrency features of YapDatabase, but it may still be usable for use cases where heavy concurrency is not required. This option might require some invasive code changes to YapDatabase.

2. Use some other database access library that does not strictly require WAL mode (e.g. FMDB). This would probably require many changes to your application code.

3. Completely close the database after each use. Closing the database would release locks and thus avoid this issue. You could work around the overhead of repeated key derivation by using raw key and salt material. This might require fewer changes, but likely eliminates many of the benefits of using YapDatabase.

4. Patch SQLCipher so that it would pass through the first portion (e.g. 32 bytes) of the database header in the clear, so iOS will identify the file as a WAL mode SQLite database. This would likely require a compiled-in database salt or the use of the standard file format header as salt itself, plus changes to the codec to avoid encrypting the first portion of the header that contains the file format version numbers. Use of a static salt would affect the security features of the database, so you would need to implement some salting of the key material externally. There isn't any terribly sensitive information in the first few bytes of the header, but this kind of patching would make the build incompatible with the standard SQLCipher library. Perhaps that is not a deal-breaker in this context.

Let me know what you think or if you have any questions.

**Comment by charlesmchen** [comment]
@sjlombardo Thanks for getting to the bottom of this.  We're interested in option 4, but have a few constraints.  In particular, we're wondering how migration for users with large pre-patch databases would work.  

If we can find an acceptable approach, would you be available to do this work?  Could we set up a call to discuss?

matthew@whispersystems.org

**Comment by sjlombardo** [comment]
Hello @charlesmchen - yes, we can setup a call to discuss the options here. I'll contact you separately via email shortly.

**Comment by brodybits** [comment]
Is there any implementation of option 4 that can be shared? Any other updates?

**Comment by sjlombardo** [comment]
Hello @brodybits - Yes, we have made changes on the prerelease branch related to option 4 in the form of new PRAMGA statements that will allow a developer to configure a portion of the header to be written in plaintext, and also explicitly provide the salt. 

The idea is that a WAL database located in a shared container can be configured so that the first part of the header is open and readable by iOS, so that iOS permits the application to hold a lock when it enters the background.

**Comment by brodybits** [comment]
> Yes, we have made changes on the prerelease branch related to option 4 in the form of new PRAMGA statements that will allow a developer to configure a portion of the header to be written in plaintext, and also explicitly provide the salt.

Thanks @sjlombardo. I see the changes in a7c459aa7775db743b92c1c2ebc8aeafb0d2c578 and 1bb4737da2e9a1f0b912185d000bb377d7b7e8b4 (old spelling error fixed in d5c2bec7688cef298292906c029d26b2c043219d), looks good. I raised a small nit in <https://github.com/sqlcipher/sqlcipher/commit/a7c459aa7775db743b92c1c2ebc8aeafb0d2c578#r27053046>, looking forward the documentation:)

**Comment by charlesmchen** [comment]
See https://github.com/signalapp/YapDatabase/pull/1

**Comment by charlesmchen** [comment]
We consider this issue resolved.  Thanks @sjlombardo and team!

**Comment by richiewoo** [comment]
When will you release this fix?

**Comment by sjlombardo** [comment]
Hello @richiewoo - This issue is resolved on the prerelease branch. These changes will be rolled into the next full release of SQLCipher.

**Comment by richiewoo** [comment]
Was this prerelease completely tested? when do you plan is the next full release of SQLCipher?

**Comment by sjlombardo** [comment]
Hello @richiewoo - yes, this was tested extensively. I don't have an exact date for the next full release of SQLCipher at this time.

**Comment by richiewoo** [comment]
@sjlombardo, I create a new DB with setting key and "PRAGMA cipher_plaintext_header_size=32", it works fine, I get the plaintext header in first 32 bytes of the DB file. But when I try to open it again with the same key, I get an error with code 26 for executing "PRAGMA cipher_version". Anything did I miss?

**Comment by sjlombardo** [comment]
Hello @richiewoo - you will need to execute `PRAGMA cipher_plaintext_header_size=32` each time the database is opened, not just the first time.

**Comment by richiewoo** [comment]
@sjlombardo , Thanks a lot for your quick response. Yes, I tried, but still failed with same error.

**Comment by developernotes** [comment]
Hi @richiewoo 

You will also need to specify the database salt on subsequent open operations (as it isn't being stored in the file header anymore in your situation). You can do so with the `PRAGMA cipher_salt = ...` command. We have an example in the test suite [here](https://github.com/sqlcipher/sqlcipher/blob/prerelease/test/crypto.test#L2566-L2594).

**Comment by richiewoo** [comment]
Hi @sjlombardo @developernotes , Thanks, it is working now by setting the database `cipher_plaintext_header_size and salt` on subsequent open operations. But do I have to cache the salt value on my own and set it to DB every time when I open it?

**Comment by sjlombardo** [comment]
Hello @richiewoo yes, if you use `cipher_plaintext_header_size` then SQLCipher can no longer store the salt in the header of the database. Your application will need to make accommodations to persist the salt elsewhere, and provide it on each use.

**Comment by AKoulabukhov** [comment]
Hi @sjlombardo , is there a way to extract `cipher_salt` from existing database which was previously used without `cipher_plaintext_header_size` ? And reopen / reserve it with new parameters?

I need it to migrate user data correctly from the app folder to SharedData.

**Comment by sjlombardo** [comment]
@AKoulabukhov You can read the salt from the first 16 bytes of the database. From there, you can store the salt and then migrate the database by opening it up, calling `PRAGMA cipher_plaintext_header_size` so that SQLCipher will set the reserved size, and then causing the header page to be written, for example by setting `PRAGMA user_version`. Test for these migrations can be found [here for DELETE](https://github.com/sqlcipher/sqlcipher/blob/d5c2bec7688cef298292906c029d26b2c043219d/test/crypto.test#L2633) journal_mode and [here for WAL](https://github.com/sqlcipher/sqlcipher/blob/d5c2bec7688cef298292906c029d26b2c043219d/test/crypto.test#L2669)

**Comment by AKoulabukhov** [comment]
@sjlombardo thank you, seems it works
