### ISSUE TITLE
Update from 3.4.1 to 3.4.2 breaks skrooge

### ISSUE THREAD

**Issue by ChrisPrior86** [sqlcipher/sqlcipher#277]
### Expected Behavior
File should open
### Actual Behavior
skrooge reports password cannot be opened - requests password
### Steps to Reproduce

SQLCipher version: 3.4.2

The skrooge developer has stated that there must be a problem with sqlcipher version 3.4.2 as they pass a command line with an inbuilt password which fails. It looks like the syntax has been altered for the sql statement.

The problem does not occur when using sqlcipher 3.4.1

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by developernotes** [comment]
Hi @ChrisPrior86 

Can you share more about the database configuration skrooge uses with regard to SQLCipher. Are you able to provide a sample database that works with SQLCipher 3.4.1, but fails with 3.4.2 along with the password for further review? Thanks!

**Comment by ChrisPrior86** [comment]
I can send you the skrooge file - I am not sure whether they wrap the sql
db as well. The password is DEFAULTPASSWORD according to the skrooge
developer.

Developer comments are below.

Hi Chris,

I can confirm.
Just to explain:
- Skrooge uses an internal database named SQLCipher
- All skg files are encrypted even if you don't give a password.
- The default password is DEFAULTPASSWORD
- To decrypt a file with SQLCipher, we must do:
    PRAGMA KEY = 'DEFAULTPASSWORD'
- This command can not fail except if the keyword KEY is not know, so if
you don't use the sqlcipher code.
- This is your case.

Could you try to create a new file and save it and reopen it with traces
(this should not work)?

Regards

Stéphane

**Comment by developernotes** [comment]
Hello @ChrisPrior86 

Please upload the skrooge file along with providing the password if different than the comment above and we will take a look further.

**Comment by ChrisPrior86** [comment]
[mum.zip](https://github.com/sqlcipher/sqlcipher/files/2254664/mum.zip)


zipped file attached

The password should be the one referenced above.

**Comment by sjlombardo** [comment]
Hello @ChrisPrior86 - I've spent a bit of time looking into this and the sample file you attached above. As far as I can tell the file you attached includes a valid sqlcipher database, but it is prefixed by the string "SKROOGE_DECRYPTE3-". 

```
zephyr:sqlcipher sjlombardo$ hexdump -C ~/Downloads/mum.skg | head -5
00000000  53 4b 52 4f 4f 47 45 5f  44 45 43 52 59 50 54 45  |SKROOGE_DECRYPTE|
00000010  33 2d 41 86 23 1b f1 2e  ea 2b e9 63 d5 82 da 19  |3-A.#....+.c....|
00000020  a6 38 55 3e 72 db 77 92  78 09 94 9a da 2c 90 4b  |.8U>r.w.x....,.K|
00000030  a4 53 42 af 6f aa 89 dd  4f ce 0e 5a c2 32 f1 87  |.SB.o...O..Z.2..|
00000040  d3 fc f6 e6 a5 9f 4d 83  e4 83 05 59 75 f5 dc 76  |......M....Yu..v|
```

As a result, it can't be opened directly by any version of SQLCipher, because SQLCipher expects the first 16 bytes of the database to contain the salt. However, if the file is modified to remove the "SKROOGE_DECRYPTE3-" then the file can be successfully opened by SQLCipher 3.4.2 without any issues at all using `pragma key = 'DEFAULTPASSWORD';`.

Looking at the skrooge source, it seems like there is some special handling for the header (e.g. https://cgit.kde.org/skrooge.git/tree/skgbasemodeler/skgservices.cpp). I'm not really familiar with the Skrooge application logic but there is a lot of different handling for various headers, e.g. "SKROOGE_ENCRYPTE3-" vs "SKROOGE_DECRYPTE3-", standard sqlite databases, a custom crypto implementation etc. It also appears that skrooge is copying databases around, etc. 

Since as far as I can tell the problem database is perfectly valid (sans the header), can be opened with the specified key, and passes an integrity check in that state, this does not appear to be a defect in SQLCipher 3.4.2, and is more likely an application logic problem. 

As such I am going to close this ticket, but feel free to post over on the discussion site (https://discuss.zetetic.net/c/sqlcipher) if there are any follow up questions.
