### ISSUE TITLE
Is macosx support gone?

### ISSUE THREAD

**Issue by shdwp** [sqlcipher/sqlcipher#292]
With `sqlcipher.xcodeproj` removed in 4.0.0, does that mean that mac support is gone? What about `macosx` folder with plist and header files?

**Comment by developernotes** [comment]
Hello @shdwp,

macOS is still fully supported by SQLCipher. However, we are no longer maintaining the `sqlcipher.xcodeproj` file as part of the Community Edition source since the [SQLCipher 4.0.0 release](https://www.zetetic.net/blog/2018/11/30/sqlcipher-400-release/). There are several reasons for dropping this; it is a somewhat archaic integration method, requires manually configured subproject references, is easy to misconfigure, and has experienced various issues with Xcode behavior in recent releases. 

You still have plenty of alternate integration options, including:

1. Create the source amalgation (sqlite3.c source file) and compile it directly into your application (this is effectively the same thing that the old `sqlcipher.xcodeproj` without the cruft). With this approach you have complete flexibility around what build options and features are enabled.
2. Utilize the Community Edition release through [CocoaPods](https://cocoapods.org/pods/SQLCipher). With CocoaPods you benefit from automated project configuration, dependency management, etc.
3. Purchase a pre-built [Commercial Edition package for macOS](https://www.zetetic.net/sqlcipher/commercial-edition-ordering) with direct online fulfillment. This provides prebuilt libraries, fast build times, and priority support directly from the SQLCipher development team.

Any of these options will provide a superior integration compared to the old `sqlcipher.xcodeproj`.
