### ISSUE TITLE
Write performance regression

### ISSUE THREAD

**Issue by joaosigma** [sqlcipher/sqlcipher#325]
### Expected Behavior
No change in performance

### Actual Behavior
Performance drops 60x (not linear)

### Steps to Reproduce
Just updated from version 3.4.2 to 4.0.0

SQLCipher version: 4.0.0

I have a large codebase which uses SQLCipher to manage 3 encrypted DBs (each one in WAL mode, with shared caching disabled) in an Android app (we have a native layer where we link against static builds of SQLCipher so we don't use any system libs). The user in the app can choose to optionally encrypt or not said DBs.

The scenario we're experiencing is rather simple: with the *exact same* code base, we simply linked against a static build of SQLCipher 4.0.0 and all of the sudden, the times needed to create the DBs jumped from 263.19 ms, 33.88 ms and 16.09 ms to 15828.50 ms, 814.09 ms and 80.71 ms. This happens even in the scenario where the user doesn't want encryption (so we end up never calling `sqlite3_key`).
Also, after reading some issues, we changed the code just to include the option `PRAGMA cipher_memory_security = OFF;`, but didn't produce any changes.

This happens with versions (from 4.0.0) up until 4.2.0.

**Comment by sjlombardo** [comment]
Hello @joaosigma - outside of limited reports of performance degradation on some devices with `cipher_memory_security` security feature enabled, which you have ostensibly ruled out, we have not had any other widespread reports of performance regressions with SQLCipher 4. Most of our internal testing shows performance to be roughly on-par with 3.x in most cases (even with memory security).

In order to look into this further we need you to provide addition information about this which is missing from your original report.

1. What specific devices (architecture, CPU, configuration) is this occurring on?
2. What exactly is happening when you are "creating the DBs", i.e. how are the database constructed, are operations are using a single long running database connection, are changes grouped in transactions, etc.
3. Are you building SQLCipher yourself, or using official Zetetic builds? What do you mean by "a static build of SQLCipher", since we do not distribute static libraries for that platform, or provide a means to build static libraries?
5. You provide three different timings, what are they actually measuring, e.g are those encrypted timings across three databases? What are the timings for non-encrypted?
6. How much data are you loading, both in terms of row count and total payload size?

**Comment by sjlombardo** [comment]
Hello @joaosigma can you please provide any of the previously requested information on this ticket? Do you still have the problem?

**Comment by joaosigma** [comment]
Hi @sjlombardo, I'm so sorry that I didn't respond before.

We tried several more times with small changes here and there and then, all of the sudden, the behavior stopped. We tried to pinpoint where or what we changed to try and replicate this, but without success (this was secondary on our list of priorities, so that's why we took so long).

As far as we are concerned, this issue is closed.

Again, sorry for the delay and thanks for your time.
