### ISSUE TITLE
'gethostuuid' is unavailable: not available on UIKit for macOS

### ISSUE THREAD

**Issue by revolter** [sqlcipher/sqlcipher#331]
### Expected Behavior

The library would be able to be used when porting an iOS app to macOS using [UIKit for macOS](https://developer.apple.com/ipad-apps-for-mac/).

I think that these lines:

https://github.com/sqlcipher/sqlcipher/blob/27d58453c6e56c3dd85e02bca379161bc69c746a/src/os_unix.c#L108-L116

should be changed to:

```objc
#if defined(__APPLE__) && ((__MAC_OS_X_VERSION_MIN_REQUIRED > 1050) || \
                           (__IPHONE_OS_VERSION_MIN_REQUIRED > 2000))
#  if (!defined(TARGET_OS_EMBEDDED) || (TARGET_OS_EMBEDDED==0)) \
       && (!defined(TARGET_IPHONE_SIMULATOR) || (TARGET_IPHONE_SIMULATOR==0)) \
       && !defined(TARGET_OS_UIKITFORMAC)
#    define HAVE_GETHOSTUUID 1
#  else
#    warning "gethostuuid() is disabled."
#  endif
#endif
```

### Actual Behavior

The library fails to build with error:

```
<...>/Pods/SQLCipher/sqlite3.c:41051:9: 'gethostuuid' is unavailable: not available on UIKit for macOS
```

on this line:

https://github.com/sqlcipher/sqlcipher/blob/27d58453c6e56c3dd85e02bca379161bc69c746a/src/os_unix.c#L6935

with description:

```
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/gethostuuid.h:39:5: 'gethostuuid' has been explicitly marked unavailable here
```

`gethostuuid.h`:
```objc
/* 29. */ #ifndef __GETHOSTUUID_H
/* 30. */ #define __GETHOSTUUID_H
/* 31. */
/* 32. */ #include <sys/_types/_timespec.h>
/* 33. */ #include <sys/_types/_uuid_t.h>
/* 34. */ #include <Availability.h>
/* 35. */
/* 36. */ #if defined(__IPHONE_OS_VERSION_MIN_REQUIRED) && (__IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_7_0)
/* 37. */ int gethostuuid(uuid_t, const struct timespec *) __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_NA, __MAC_NA, __IPHONE_2_0, __IPHONE_5_0, "gethostuuid() is no longer supported");
/* 38. */ #else
/* 39. */ int gethostuuid(uuid_t, const struct timespec *) __OSX_AVAILABLE_STARTING(__MAC_10_5, __IPHONE_NA);
/* 40. */ #endif
/* 41. */ 
/* 42. */ #endif /* __GETHOSTUUID_H */
```

### Steps to Reproduce

- Create an iOS app
- Add SQLCipher as a pod dependency
- Install beta macOS Catalina 10.15
- Install beta Xcode 11
- Go to project settings
- Select the iOS app target
- Go to the "General" tab > "Deployment Info" section
- Turn on the "Mac" checkbox
- Try to build the app

SQLCipher version: 3.4.2

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by revolter** [comment]
Related to https://github.com/Tencent/wcdb/issues/531.

**Comment by sjlombardo** [comment]
Hello @revolter - thanks for getting in touch about this. We've obeserved the same thing in our own testing as well. We're currently monitoring to see if/how this gets fixed upstream in SQLite, since the same condition applies in the base software.

In the meantime as a workaround, can you try to add -DTARGET_OS_EMBEDDED to your C flags?

**Comment by revolter** [comment]
I added `-DTARGET_OS_EMBEDDED` to the `Pods-<TargetName>.debug.xcconfig` but it gets ignored. I previously tried adding it to my project target's Other C Flags build setting.

**Comment by revolter** [comment]
I think that something else resets or forces this exact macro to `0`, even if I explicitly use `-DTARGET_OS_EMBEDDED=1`.

**Comment by sjlombardo** [comment]
@revolter thanks for getting back to us. One of my colleagues has opened up a thread about this on the SQLite list with the hope of getting a change included upstream to resolve this issue, since this problem actually affects SQLite as a whole. We'll be monitoring the response. Hopefully the SQLite project will adopt the fix (the ideal situation), else we will make the necessary change in SQLCipher directly for an upcoming release (the backup plan). We'll update this issue as we have additional information. In the meantime making the change to your sources locally is a safe workaround.

**Comment by revolter** [comment]
Thank you very much for the update!

**Comment by himanshujain18** [comment]
Hi @revolter ,
I got the exact same error while building sqlcipher for UIKitForMac. The error is resolved when I change the source file "sqlcipher/src/os_unix.c" exactly as you mentioned above.

Though the build is successfull, I think it is not correctly build for UIKitForMac. The reason is I see a warning saying that - 
"ld: warning: building for macOS, but linking in object file (.libs/sqlite3.o) built for UIKitForMac"

Can you please help me figure out what I am doing wrong here.

My CFLAGS AND LDFLAGS values are as follows : 

CFLAGS='-DSQLITE_HAS_CODEC -isysroot /Applications/Xcode11-beta3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fno-common -arch x86_64 -target x86_64-apple-ios13.0-macabi -isystem /Applications/Xcode11-beta3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/iOSSupport/usr/include -iframework /Applications/Xcode11-beta3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/iOSSupport/System/Library/Frameworks'

LDFLAGS='-framework Security -framework Foundation -target x86_64-apple-ios13.0-macabi -L/Applications/Xcode11-beta3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/uikitformac'

**Comment by revolter** [comment]
@himanshujain18, I don't know how to help you.

**Comment by revolter** [comment]
@sjlombardo, I tried setting `TARGET_OS_EMBEDDED` again and I'm pretty sure it doesn't work because `/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/TargetConditionals.h` re-defines it as `0`.

**Comment by ahmedk92** [comment]
Any update on this? I'm having the same problem.

**Comment by R4N** [comment]
An adjustment has been made in the upstream SQLite source which will accomodate excluding UIKit for macOS from the gethostuuid() conditional.  This adjustment will be included at some point in a future version of SQLCipher.  Until that point you can utilize the proposed workaround as mentioned by @revolter -- adjusting the preprocessor conditional to account for TARGET_OS_UIKITFORMAC:

```
#if defined(__APPLE__) && ((__MAC_OS_X_VERSION_MIN_REQUIRED > 1050) || \
                           (__IPHONE_OS_VERSION_MIN_REQUIRED > 2000))
#  if (!defined(TARGET_OS_EMBEDDED) || (TARGET_OS_EMBEDDED==0)) \
       && (!defined(TARGET_IPHONE_SIMULATOR) || (TARGET_IPHONE_SIMULATOR==0)) \
       && (!defined(TARGET_OS_UIKITFORMAC) || (TARGET_OS_UIKITFORMAC==0))
#    define HAVE_GETHOSTUUID 1
#  else
#    warning "gethostuuid() is disabled."
#  endif
#endif
```

@revolter correct assumption about TARGET_OS_EMBEDDED, unfortunately that doesn't work for the reasons you mentioned

**Comment by chrisballinger** [comment]
FWIW that target conditional is now called `TARGET_OS_MACCATALYST`, although `TARGET_OS_UIKITFORMAC` still works.

**Comment by sjlombardo** [comment]
There is a [fix for this issue](https://sqlite.org/src/info/3bcb9cc104e0265a) was included by the [SQLite team](https://www.mail-archive.com/sqlite-users@mailinglists.sqlite.org/msg116842.html) in SQLite 3.30.0. 

Since SQLCipher 4.3.0 is based on SQLite 3.30.1, this is therefore included in the latest SQLCipher release. The solution is to define `HAVE_GETHOSTUUID=0` when building for Mac Catalyst (i.e. `-DHAVE_GETHOSTUUID=0`).

**Comment by chrisballinger** [comment]
@sjlombardo For what it's worth, I think the upstream fix in SQLite is incomplete, because it doesn't compile correctly out of the box. The old ifdef logic is simply incorrect and doesn't take into account `TARGET_OS_MACCATALYST`. I'll try submitting my #342 patch upstream instead and see if it gets anywhere.

**Comment by sjlombardo** [comment]
@chrisballinger We fully agree that the upstream fix is not ideal. In fact, Micah from our team tried to suggest a more complete change (that would work out of the box) last year on two separate occasions:

http://sqlite.1065341.n5.nabble.com/Adapt-HAVE-GETHOSTUUID-conditional-for-UIKit-for-macOS-td107783.html

http://sqlite.1065341.n5.nabble.com/SQLite-version-3-30-0-in-about-two-weeks-td108708.html#a108722

Unfortunately these solutions were were rejected in favor of the current upstream implementation. Our goal is still to minimize differences with upstream, but if you can convince the SQLite maintainers to accept a more complete patch (e.g. using TARGET_OS_MACCATALYST), we would certainly be happy to see it!

**Comment by chrisballinger** [comment]
@sjlombardo Ahh bummer, hope we can get some traction this time around. Here's my attempt: https://sqlite.org/forum/forumpost/803387a1c5

**Comment by sjlombardo** [comment]
@chrisballinger totally, fingers crossed! We'll keep an eye on that thread!

**Comment by jarulvalan** [comment]
@sjlombardo , @revolter ,

i got the same error while building sqlcipher-4.4.1 for mac catalyst on MacOS 11.0.

./configure --with-crypto-lib=commoncrypto --enable-tempstore=yes --host x86_64-apple-darwin CFLAGS="-DSQLITE_HAS_CODEC -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -fno-common -arch x86_64 -target x86_64-apple-ios13.0-macabi -isystem /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/iOSSupport/usr/include -iframework /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/iOSSupport/usr/include/System/iOSSupport/System/Library/Frameworks -fembed-bitcode-marker" LDFLAGS="-framework Security -framework Foundation"

Error : 

libtool: link: gcc -dynamiclib  -o .libs/libsqlcipher.0.dylib  .libs/sqlite3.o   -framework Security -framework Foundation -lz  -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -arch x86_64   -framework Security -framework Foundation -install_name  /usr/local/lib/libsqlcipher.0.dylib -compatibility_version 9 -current_version 9.6 -Wl,-single_module
ld: building for macOS, but linking in object file built for Mac Catalyst, file '.libs/sqlite3.o' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libsqlcipher.la] Error 1

can you please help to figure the error and how to resolve that?

**Comment by R4N** [comment]
@jarulvalan 

This error message looks unrelated to the issue reported on this GitHub issue (which is now resolved/closed with the solution mentioned in an earlier comment by my colleague: https://github.com/sqlcipher/sqlcipher/issues/331#issuecomment-568080577). I see you cross posted to the [SQLCipher discussion forum](https://discuss.zetetic.net/t/ld-building-for-macos-but-linking-in-object-file-built-for-mac-catalyst-file-libs-sqlite3-o-for-architecture-x86-64/4699) which is the appropriate place for your type of question as it's a build configuration question/error rather than a defect/issue with SQLCipher.
