### ISSUE TITLE
Crypto provider init failure is being silently ignored

### ISSUE THREAD

**Issue by lgrahl** [sqlcipher/sqlcipher#347]
### Expected Behavior

Fail explicitly when a crypto provider did not return `SQLITE_OK` in its initialisation routine.

### Actual Behavior

When opening a database and providing a key via `PRAGMA key = 'secret';`, crypto provider initialisation failures are being silently ignored.

As a consequence, in case a crypto provider initialisation routine fails while creating a new database, the database is being stored in plaintext.

### Steps to Reproduce

Patch the default crypto provider (`sqlcipher_openssl_ctx_init`) to return `SQLITE_ERROR`. Compile it. Run the CLI with `sqlcipher foo.db`:

> PRAGMA key = 'secret';
SELECT count(*) FROM sqlite_master;
CREATE TABLE IF NOT EXISTS lorem (info TEXT);
.exit

The resulting `foo.db` is not encrypted and there was no indication that something failed.

SQLCipher version: [750f5e32474ee23a423376203e671cab9841c67a](https://github.com/sqlcipher/sqlcipher/tree/750f5e32474ee23a423376203e671cab9841c67a)

**Comment by sjlombardo** [comment]
Hello @lgrahl - thanks for reporting this issue. SQLCipher was propagating the error up, but the problem was that the PRAGMA handler was ignoring the result code. We have added a fix for this into the SQLCipher 4.3.0 release which forces the database pager into an error state if initialization fails, resulting in the database connection being unusable.
