### ISSUE TITLE
Please un-deprecate "PRAGMA fast_kdf_iter"

### ISSUE THREAD

**Issue by ngg** [sqlcipher/sqlcipher#361]
We've been using SQLCipher v3 with https://github.com/sqlcipher/sqlcipher/pull/245 for increased security parameters. We have now successfully migrated to v4.3.0, but we need to set (among other parameters) fast_kdf_iter to 10 to be able to load older databases. As our application uses large database files on customers' machines, we cannot easily migrate the databases themselves. (There might be not enough space on the machine, or the customer might simply not use the application for years, but later it needs to access the database).
I'd like to ask you to please keep fast_kdf_iter modifiable.
Thanks!

**Comment by sjlombardo** [comment]
Hello @ngg, thanks for getting in touch. I'm afraid we don't have any intent of removing the deprecation on fast_kdf_iter. This was a legacy setting, and to be honest wouldn't have even been included in the first place other than to support a very specific migration scenario for version 2.0-beta release users 8 years ago. The time has come to remove it. It was not really appropriate for #245 to change that default setting, and we clearly commented there that SQLCipher would not be using that pull.

That said, fast_kdf_iter still works in the current release (even though it logs a deprecation warning). Since you are already using a custom version of SQLCipher you've built yourself, our recommendation would be to adjust your application to migrate over to using the standard SQLCipher settings. This should probably not be that difficult to do, and would ensure long term compatibility options going forward.

**Comment by ngg** [comment]
It was probably a really bad idea for us to use that patch when we migrated from non-encrypted SQLite to SQLCipher, but we did and we cannot undo that.
We can easily have new databases created using the new defaults, but the problem is with migration. Our application is deployed on lots of customer PCs and phones, and we cannot easily migrate those. For example on phones, the migration could take a long time which would be a really bad user experience. Some of our users might not even start our application for a long time. However we will still want to support loading these databases in the future (at least for the next 2-4 years) and we'd like to be able to upgrade SQLCipher and SQLite to newer versions as well. So if you'll remove that pragma, I'll think we'll have no other choice but to patch it back in our fork.

**Comment by sjlombardo** [comment]
Hello @ngg, yes, I understand. In that case it does sound like it might require some patching on your end long term. Even so, wouldn't it still be desirable to get the ball rolling towards migrating users to standard settings? Unless your databases are really very large it should be possible to perform some migration without a terrible user experience.
