### ISSUE TITLE
Failed to open database with sqlcipher 4.x after saving with 3.x but with 4.0 default params

### ISSUE THREAD

**Issue by anthonybilinski** [sqlcipher/sqlcipher#363]
### Expected Behavior
1) A database created by sqlcipher 3.4.2 can be saved with sqlcipher 4.x parameters, and then opened by sqlcipher 4.3.0.

### Actual Behavior
Creating a database with sqlcipher 3.4.2, but setting sqlcipher 4.0 defaults works, and can be read by sqlcipher 3.4.2 only if those parameters are re-set, as expected, but sqlcipher 4.3.0 cannot decrypt the database.
### Steps to Reproduce
1) Create the database using sqlcipher 3.4.2, then set params that are 4.0 defaults for compatibility:
```
PRAGMA key = "x'd3dbe138d2dcb1236b9afd9529004ab78ae1ef4cedb59b5f7ad88a39b42a8f40'";
PRAGMA cipher_page_size = 4096;
PRAGMA kdf_iter = 256000;
PRAGMA cipher_hmac_algorithm = HMAC_SHA512;
PRAGMA cipher_kdf_algorithm = PBKDF2_HMAC_SHA512;
CREATE TABLE test(int);
select * from test;

```
2) Try reading this database with sqlcipher 4.3.0:
```
sqlite> PRAGMA key = "x'd3dbe138d2dcb1236b9afd9529004ab78ae1ef4cedb59b5f7ad88a39b42a8f40'";
sqlite> PRAGMA cipher_page_size = 4096;
sqlite> PRAGMA kdf_iter = 256000;
sqlite> PRAGMA cipher_hmac_algorithm = HMAC_SHA512;
sqlite> PRAGMA cipher_kdf_algorithm = PBKDF2_HMAC_SHA512;
sqlite> select * from test;
Error: file is not a database
```
3) Using 3.4.2 with the same params continues to work, meaning this database is now only accessible from 3.4.2, rather than from both 3.4.2 and 4.3.0.

SQLCipher version: 3.4.2. and 4.3.0

I've gotten the required params from https://www.zetetic.net/blog/2018/11/30/sqlcipher-400-release/ and looked at the migration info here: https://www.zetetic.net/sqlcipher/sqlcipher-api/#sqlcipher_export but it still seems like I'm missing something.

Are there other params that need to be set for me to access this database with both 3.4.2 and 4.3.0 using the 4.0 default params?

**Comment by sjlombardo** [comment]
@anthonybilinski SQLCipher 3 did not support PRAGMA cipher_hmac_algorithm or PRAGMA cipher_kdf_algorithm. As a result those PRAGMA don't do anything when invoked against a SQLCipher 3 library. In other words, since they have no effect HMAC_SHA1 and PBKDF2_HMAC_SHA1 are used. 

You could open the database created as you specified with SQLCipher 3 like this instead:

```
sqlite> PRAGMA key = "x'd3dbe138d2dcb1236b9afd9529004ab78ae1ef4cedb59b5f7ad88a39b42a8f40'";
sqlite> PRAGMA cipher_page_size = 4096;
sqlite> PRAGMA kdf_iter = 256000;
sqlite> PRAGMA cipher_hmac_algorithm = HMAC_SHA1;
sqlite> PRAGMA cipher_kdf_algorithm = PBKDF2_HMAC_SHA1;
sqlite> select * from test;
```

**Comment by anthonybilinski** [comment]
Aha that explains it, thanks! Does that mean there's no way for sqlcipher 3 to open a database encrypted with sqlcipher 4 default parameters?

**Comment by sjlombardo** [comment]
@anthonybilinski yes, that is correct. Support for SHA-256 and SHA-512 were added in SQLCipher 4, so you can't open a SQLCipher 4 database from SQLCipher 3 with default parameters. If you need to do that (i.e. have a database that is shared between both versions) then you can either use SQLCipher 3 default compatibility (PRAGMA cipher_compatibility = 3) or otherwise ensure that they are using mutually supported settings.

**Comment by anthonybilinski** [comment]
Got it, that again.
