### ISSUE TITLE
why msvc can't build 

### ISSUE THREAD

**Issue by moneyfengcn** [sqlcipher/sqlcipher#388]
my OS is windows 10 pro and visual studio 2019 pro 

run this command 
 nmake /f Makefile.msc TOP=..\sqlite

-----

sqlite3.c(3541) : error C2143:
sqlite3.c(3541) : error C2143:
sqlite3.c(3541) : error C2059:
sqlite3.c(3541) : error C2059:
sqlite3.c(3543) : error C2143:
sqlite3.c(3543) : error C2143:
sqlite3.c(3543) : error C2059:
sqlite3.c(3543) : error C2059:
sqlite3.c(3676) : error C2016:
sqlite3.c(3676) : error C2061:
sqlite3.c(3677) : error C2373:

...
NMAKE : fatal error U1077

**Comment by developernotes** [comment]
Hi @moneyfengcn 

We reserve GitHub Issues for reporting defects in the SQLCipher library itself. Since you question is about building the software on a specific platform, we would suggest you consider posting to the [SQLCipher Community Discuss site](https://discuss.zetetic.net/c/sqlcipher) instead. Thanks!
