### ISSUE TITLE
github SQLCipher build old version I need latest

### ISSUE THREAD

**Issue by TechComet** [sqlcipher/sqlcipher#389]
SQLCipher version:
I download latest version
https://github.com/sqlcipher/sqlcipher/tree/v4.4.3

```
$ ./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC" \ LDFLAGS="-lcrypto"

$ make
```

It's work but build `sqlcipher version 3.34.1`
I need build `sqlcipher version 4.4.3`

**Comment by R4N** [comment]
Looks like you're outputting the SQLite version instead of the SQLCipher version. You'll want to use [PRAGMA cipher_version;](https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_version) to view the SQLCipher version.

We reserve GitHub issues for reporting bugs/defects within SQLCipher. Please post to the [SQLCipher discussion forum](https://discuss.zetetic.net/c/sqlcipher/) with any other queries.
