### ISSUE TITLE
Cannot perform a backup from encrypted to encrypted

### ISSUE THREAD

**Issue by matteoPhre** [sqlcipher/sqlcipher#393]
I'm updating to the latest version of sqlcipher (4.4.2 or 4.4.3) from v3.20.1. Previously the backup was working, now i'm not able to perform an online backup.

### Steps to Reproduce
./sqlcipher " {databasePath} "PRAGMA KEY = '{databaseKey}'" ".backup {backupTempPath}" "ATTACH DATABASE '{backupPath}' AS encrypted KEY '{databaseKey}'" "SELECT sqlcipher_export('encrypted')" "DETACH DATABASE encrypted""
Error: backup is not supported with encrypted databases

The same command, using sqlcipher 3.20.1 is working fine.

I've tried to set the cipher_compatibility = 3, but doesn't help. The only way to manage the "backup" of an encrypted database is to avoid the backup call, executing the ATTACH giving the same key, calling the sqlcipher_export() and DETACH it.

Is this the correct way? Because i saw in the source of backup.test that the backup from encrypted to encrypted was enabled again.

SQLCipher version: 4.4.2 & 4.4.3

OS: tested on Windows 10, Debian 10 (armv7), Ubuntu 18 (x64) with openssl(1.1.1d) and sqlcipher compiled for each targets.

**Comment by sjlombardo** [comment]
Hello @matteoPhre - I've commented on this behavior on your other post here:

https://discuss.zetetic.net/t/cannot-perform-a-backup-from-encrypted-to-encrypted/5051/2

I will close this ticket now since it's cross posted, and we can converse further on the discussion site if you have other questions or comments related to this.
