### ISSUE TITLE
Vulnerabilities  openssl in openssl 1.1.1j

### ISSUE THREAD

**Issue by TangHuaiZhe** [sqlcipher/sqlcipher#409]
### Expected Behavior

Hi,

We found the following vulnerabilities about OpenSSL (1.1.1j) in sqlcipher 4.4.3 when we using security scanning tool [ProteCode](https://protecode-sc.com/login/?next=/).

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/7965577/140692421-cdc55e38-10e5-436d-b651-8828cf395873.png">

[CVE-2021-3711](https://nvd.nist.gov/vuln/detail/CVE-2021-3711)

[CVE-2021-3712](https://nvd.nist.gov/vuln/detail/CVE-2021-3712)

[CVE-2021-3450](https://nvd.nist.gov/vuln/detail/CVE-2021-3450)

[CVE-2021-3449](https://nvd.nist.gov/vuln/detail/CVE-2021-3449)

Will these vulnerabilities really affect SQLCipher?
I read the [issue](https://github.com/sqlcipher/sqlcipher/issues/396) but I'm still not sure.

Look forward to your professional advice.

Thanks!

### Steps to Reproduce

SQLCipher version: 4.4.3

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by developernotes** [comment]
Hi @TangHuaiZhe 

SQLCipher is not affected by these vulnerabilities because it does not utilize SM2, public key cryptographic operations, TLS, or X.509. Also, the latest version of SQLCipher is 4.5.0. For builds which utilize OpenSSL, we are using version 1.1.1l. If you have any further questions, please feel free to post to the [SQLCipher Community Discuss Forum](https://discuss.zetetic.net/c/sqlcipher). Thanks!

**Comment by TangHuaiZhe** [comment]
Hi @developernotes, thanks for your professional response!
