### ISSUE TITLE
sqlcipher has no maintainer in debian 

### ISSUE THREAD

**Issue by TNTBOMBOM** [sqlcipher/sqlcipher#422]
The maintainer in debian distro is no longer doing that: 

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=961598

> I request an adopter for the sqlcipher package. I no longer am
> involved in SQLCipher development nor have time to maintain this
> package.

Package Info in debian: 

https://tracker.debian.org/pkg/sqlcipher

Hope can be maintained from upstream, Since debian (with its derivatives) the most used/famous distro in GNU/Linux world.

ThX!

**Comment by sjlombardo** [comment]
Hi @TNTBOMBOM - thanks for making us aware of this.

Unfortunately, our team was not involved in the original package publication, and we don't have any tangible experience maintaining Debian packages. The documentation around it looks fairly involved. 

To complicate matters, the last version of that Debian package (3.4.1) that was released in 2021 was over 4 years behind upstream at the time of publication. It is now 12+ versions behind current and the default settings are incompatible with any official versions released since 2018. Because of this an uncoordinated upgrade could cause major incompatibles for any existing users.

Without the experience on how to maintain, publish, supersede, or support migrations, it would be exceptionally difficult and high risk for us to take this over upstream. It might be better if someone out there in the community who is an experienced existing Debian maintainer would volunteer.

Barring that, perhaps the better approach for users would be to download the SQLCipher sources and build for themselves? This way they would have full control of the software and environment.  

Let us know what you think.

**Comment by TNTBOMBOM** [comment]
> Without the experience on how to maintain, publish, supersede, or support migrations, it would be exceptionally difficult and high risk for us to take this over upstream. It might be better if someone out there in the community who is an experienced existing Debian maintainer would volunteer.

Can it be at least available as .dpkg in your website? no need to be in debian.

> Barring that, perhaps the better approach for users would be to download the SQLCipher sources and build for themselves? This way they would have full control of the software and environment.

maybe but not the best option as this is need an experienced user to do this and time consuming (specially it need to be upgraded from time to time) not like installing a ready package.
