### ISSUE TITLE
A possible data race

### ISSUE THREAD

**Issue by ryancaicse** [sqlcipher/sqlcipher#426]
Should `g.serverHalt = 1` be protected b lock `g.serverMutex`?
https://github.com/sqlcipher/sqlcipher/blob/0663d8500204e14bd2bb0ca25162d91e4555528d/src/test_server.c#L508-L513

Like this.

```
 void sqlite3_server_stop(void){ 
   pthread_mutex_lock(&g.serverMutex); 
   g.serverHalt = 1; 
   pthread_cond_broadcast(&g.serverWakeup); 
   pthread_mutex_unlock(&g.serverMutex); 
 } 
```

**Comment by sjlombardo** [comment]
Hello @ryancaicse sorry for the delayed response on this. After a quick review of the server implementation, I don't think that the update to serverHalt needs to be guarded by the serverMutex since it is declared volatile and only used to control the thread run loop.

That said I'm not deeply familiar with that extension because it isn't really a core "feature" of SQLite or a supported extension for SQLCipher. 

Since the test_server.c is part of the upstream SQLite sources, if you are thinking about using it you could consider posting a general question (i.e. not related to SQLCipher) up to the [SQLite Forum](https://sqlite.org/forum/forummain).
