### ISSUE TITLE
Error: file is not a database should not appear or be more user friendly when trying to open version 3 database with version 4.4.3

### ISSUE THREAD

**Issue by WolfgangFahl** [sqlcipher/sqlcipher#437]
### Expected Behavior
Open database version 3 or report wrong version
### Actual Behavior
Error: file is not a database

### Steps to Reproduce
Try opening a version 3 database from command line using correct version 3 key.

SQLCipher version:
SQLite version 3.34.1 2021-01-20 14:10:07 (SQLCipher 4.4.3 community)

**Comment by WolfgangFahl** [comment]
```
#PRAGMA cypher_migrate 
```
works on this database to i wonder why this is not automatically tried/done or can be specified on the command line

**Comment by sjlombardo** [comment]
There is a very significant overhead to `cipher_migrate` because it needs to attempt to open the database for each version settings. As a result SQLCipher doesn't try to automatically migrate databases. Instead, an application can either determine itself which version is in use (i.e. via some separate preference tracking), or use the process described here to automatically attempt migration when a key fails.

https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_migrate

**Comment by WolfgangFahl** [comment]
a command line option for both the key and the migration would imho be good - it's a bit awkard to have to pipe in these commands. 
```bash
cat << EOF | sqlcipher $encdb
PRAGMA key='$key';
PRAGMA cipher_migrate;
.schema
select count(*) from sqlite_master;
ATTACH DATABASE '$decb' AS plaintext KEY '';
SELECT sqlcipher_export('plaintext');
DETACH DATABASE plaintext;
EOF
fi
```

**Comment by sjlombardo** [comment]
Hello @WolfgangFahl I certainly understand and respect your opinion about this. I just want to be direct about the complexities involved and explain the reason that it is extremely unlikely that we will include automatic upgrade functionality in SQLCipher in the near future.
