### ISSUE TITLE
Vulnerability in OpenSSL CVE-2022-0778

### ISSUE THREAD

**Issue by rickhenderson** [sqlcipher/sqlcipher#441]
I'm just really curious more than anything else and learning how all this fits together.
I'm using sqlcipher.dll in a .NET project, and I see your code includes OpenSSL.

If there are vulnerabilities in OpenSSL do they affect sqlcipher? 

How can I tell which version of OpenSSL the lastest build of sqlcipher is using?

**Comment by sjlombardo** [comment]
The impact is context dependent. Historically the vast majority of OpenSSL CVEs affect either TLS or public key encryption. SQLCipher doesn't use those, only a limited set of very stable algorithms exposed through libcrypto. As a result most OpenSSL CVEs do not affect SQLCipher. For example, with CVE-2022-0778, because SQLCipher doesn’t use anything related to TLS, certificate parsing, public key parsing, or Elliptic Curve cryptography, there is no impact. 

If there were a vulnerability in OpenSSL affecting AES-256-CBC, HMAC (SHA1, SHA256, or SHA512), PBKDF2, etc, then SQLCipher might be affected. In that case we would prioritize an update to a new version of OpenSSL. 

With regard to our official packages use of OpenSSL, you can keep track of that in the release notes published on the Discussion Site. These note the version of OpenSSL used when we upgrade.

 https://discuss.zetetic.net/c/sqlcipher/updates/14

**Comment by rickhenderson** [comment]
Thank you so much! Perfect information and a great way to keep people updated.

**Comment by SagarPanwala** [comment]
@rickhenderson @sjlombardo 
I'm  not raising the new issue, adding the comment because my problem is little bit of doubt. 
Why sqlcipher needs openssl , as per my understanding  open ssl is needed for networking  call and sql is used to store data locally. 

Background  for above doubt :
I uploaded an apk to a tool ostorlab , which is useful to find the vulnerability in the build. It says open ssl 1.1.1 is outdated and I've checked that latest sqlcipher 4.5.3 has open ssl 1.1.1. 
Do we have any workarounds to solve this?

Appreciate  the efforts you guys are putting in sqlcipher.

**Comment by sjlombardo** [comment]
Hello @SagarPanwala - SQLCipher does not use OpenSSL for networking at all. The only utilization of OpenSSL is for "libcrypto" which provides basic cryptographic APIs for AES, HMAC, SHA*, and PBKDF2. SQLCipher has not been impacted by any recent OpenSSL CVEs. I am not sure what criteria ostorlab labs uses, but the 1.1.1 is still supported by OpenSSL because it is an LTS release. It sounds like perhaps that should be reported to ostorlab as an error in their database.

**Comment by rickhenderson** [comment]
@SagarPanwala A lot of the use of OpenSSL is to encrypt network traffic, but the tools in OpenSSL dealing with encrypting data (as SJL has mentioned) are the ones used  in libcrypto and SQLCipher.

Basically, if I understand correctly, SQLCipher is only using the mathmatical encryption algorithms from OpenSSL. Anything else wrong with OpenSSL in other areas would not affect SQLCipher.

**Comment by AS0820075980** [comment]
❤️

Chaiwat oppo A16

ในวันที่ ศ. 21 เม.ย. 2023 00:28 น. Rick Henderson ***@***.***>
เขียนว่า:
