### ISSUE TITLE
qSqlcipher Qt plugin with qsqlquery function taking more time for execution 

### ISSUE THREAD

**Issue by kuldipsomwanshi** [sqlcipher/sqlcipher#446]
I am using the QSqlcipher plugin and creating qsqldabase conn and using it with qsqlquery functions mainly conn.exec("query"); then observed that taking very much time to execute with sqlcipher encrypted database.  But when I am using same qsqlquery function with QSqlite3 plaintext then it taking minimum time for query execution.

I have gone through with the suggestions of optimization.
performance speed and optimization here:
https://www.zetetic.net/sqlcipher/performance/

And some information about how SQLCipher compares here:
https://discuss.zetetic.net/t/how-does-sqlcipher-compare-to-other-sqlite-encryption-extensions/2864

**Comment by sjlombardo** [comment]
Hello @kuldipsomwanshi. Unfortunately there isn't enough to go on here. SQLCipher does have additional overhead because of it's security features (encryption, key derivation, tamper evidence, etc). These features aren't without performance penalty. Usually the performance impact is relatively small for a well designed application, but it can vary significantly based on the size of the database, the types of queries being executed, concurrency, etc. The performance document you linked provides a sensible starting point for troubleshooting performance problems. If you have exhausted all of the suggestions, then you would need to start doing very specific benchmarking.

This topic is better suited for the SQLCipher discussion site here:

https://discuss.zetetic.net/c/sqlcipher/5
