### ISSUE TITLE
Setting key in an `IMMEDIATE` transaction causes `file is not a database`

### ISSUE THREAD

**Issue by name1e5s** [sqlcipher/sqlcipher#455]
### Expected Behavior

`PRAGMA key =` works fine in an IMMEDIATE transaction.

### Actual Behavior

Setting key in an `IMMEDIATE` transaction causes `file is not a database`.

Open an encrypted database and `BEGIN IMMEDIATE;` directly also result in a `file is not a database` error.

### Steps to Reproduce

```
# here kv_2.db is not exist.
➜  sqlcipher kv_2.db
SQLite version 3.39.2 2022-07-21 15:24:47 (SQLCipher 4.5.2 community)
Enter ".help" for usage hints.
sqlite> BEGIN IMMEDIATE;
sqlite> PRAGMA key = '114514';
ok
sqlite> COMMIT;
sqlite> PRAGMA journal_mode = 'WAL';
Parse error: file is not a database (26)
# here kv.db is an database with key = '114514'
➜  sqlcipher kv.db
SQLite version 3.39.2 2022-07-21 15:24:47 (SQLCipher 4.5.2 community)
Enter ".help" for usage hints.
sqlite> BEGIN IMMEDIATE;
Runtime error: file is not a database (26)
```

SQLCipher version:

4.5.2

*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by developernotes** [comment]
Hello @name1e5s 

The behavior you are seeing is the expected behavior. Setting the key must be performed as the first step if you wish to create a SQLCipher-encrypted database.

We reserve GitHub Issues for tracking defects within the software library itself. To discuss this topic further, please consider posting to the [SQLCipher Community Discuss site](https://discuss.zetetic.net/c/sqlcipher). Thanks!
