### ISSUE TITLE
libtool fails on aarch64 

### ISSUE THREAD

**Issue by einarjon** [sqlcipher/sqlcipher#456]
I was trying to build this for imx8 ARM64, but it fails on libtool.
Changing the file Makefile.in to add --tag=CC in LTLINK fixes the issue.

### Expected Behavior
aarch64 build should work

### Actual Behavior
aarch64  build fails

### Steps to Reproduce
Build for aarch64. Watch it fail.

SQLCipher version:
master

Patch below.
--
```
diff --git a/Makefile.in b/Makefile.in
index ad4be7b..b050103 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -179,7 +179,7 @@ ALLOWRELEASE = @ALLOWRELEASE@
 
 # libtool compile/link/install
 LTCOMPILE = $(LIBTOOL) --mode=compile --tag=CC $(TCC) $(LTCOMPILE_EXTRAS)
-LTLINK = $(LIBTOOL) --mode=link $(TCC) $(LTCOMPILE_EXTRAS) @LDFLAGS@ $(LTLINK_EXTRAS)
+LTLINK = $(LIBTOOL) --mode=link --tag=CC $(TCC) $(LTCOMPILE_EXTRAS) @LDFLAGS@ $(LTLINK_EXTRAS)
 LTINSTALL = $(LIBTOOL) --mode=install $(INSTALL)
 
 # You should not have to change anything below this line
```

**Comment by sjlombardo** [comment]
Hello @einarjon - Instead of making a change to Makefile.in could you try adding the flag to the LDFLAGS variable while configuring, e.g.

```
./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC" LDFLAGS="--tag=CC"
```

We typically try to avoid divergent unnecessary changes to files that are sourced from upstream SQLite. If the above option doesn't work for you, the next step would be to download the sqlite-src-3400000.zip from the [SQLite Download page](https://sqlite.org/download.html) and see if you run into the same problem.

**Comment by einarjon** [comment]
Makes sense. I have modified the yocto recipe to handle this.
