### ISSUE TITLE
2 files found with path `'lib/arm64-v8a/libsqlcipher.so'`

### ISSUE THREAD

**Issue by priyank-huma** [sqlcipher/sqlcipher#467]
Error:
```
2 files found with path 'lib/arm64-v8a/libsqlcipher.so' from inputs:
 - /Users/priyank/.gradle/caches/transforms-3/d0db61ef2d39c78a32a9106267aa6d01/transformed/android-database-sqlcipher-4.5.3/jni/arm64-v8a/libsqlcipher.so
 - /Users/priyank/.gradle/caches/transforms-3/438ade97106fd0d78572fef283fee359/transformed/sqlcipher-android-4.5.2/jni/arm64-v8a/libsqlcipher.so
If you are using jniLibs and CMake IMPORTED targets, see
https://developer.android.com/r/tools/jniLibs-vs-imported-targets
```

Library SQLCipher version: `net.zetetic:sqlcipher-android:4.5.2`
Project SQLCipher version: `net.zetetic:android-database-sqlcipher:4.5.1`

**Comment by developernotes** [comment]
Hi @priyank-huma,

Can you please provide more information regarding your report?

**Comment by priyank-huma** [comment]
@developernotes 
We are currently utilizing the `net.zetetic:android-database-sqlcipher:4.5.1` dependencies in our project. However, we have encountered an issue due to a conflict with another third-party library that relies on `net.zetetic:sqlcipher-android:4.5.2` dependencies. The problem arises from both libraries generating the `lib/arm64-v8a/libsqlcipher.so` file in different locations, causing conflicts within our project.

**Comment by developernotes** [comment]
Hi @priyank-huma,

We advise against linking multiple versions of SQLCipher within an application due to the potential for database corruption given certain usage scenarios. You will want to adjust your dependencies so you are only using either `net.zetetic:android-database-sqlcipher` which is the legacy edition of the library, or migrate to `net.zetetic:sqlcipher-android`, the latest version of SQLCipher for Android.
