### ISSUE TITLE
Potential Memleak in sqlite3recover.c

### ISSUE THREAD

**Issue by icy17** [sqlcipher/sqlcipher#487]
In ext/recover/sqlite3recover.c: 982, calling [sqlite3_open_v2](https://github.com/sqlcipher/sqlcipher/blob/master/ext/recover/sqlite3recover.c#L982) without releasing parameter 2 cause memleak

**Comment by sjlombardo** [comment]
Hello @icy17 - It looks like this issue is rooted in the upstream SQLite project, i.e. the code originated in SQLite and was not modified by SQLCipher. Therefore it would be better to be reported to SQLite instead. This usually involves identifying / reproducing the issue with standard SQLite (completely excluding SQLCipher), documenting the issue, and then submitting a summary and/or patch to the SQLite maintainers. If and when appropriate changes are applied to upstream SQLite, the SQLCipher project would then incorporate those fixes as part of our standard release workflow.
