### ISSUE TITLE
unseen char in shell.c.in

### ISSUE THREAD

**Issue by liuyug** [sqlcipher/sqlcipher#506]
### Expected Behavior
remove unseen char
### Actual Behavior
static const char *zBomUtf8 = "\xef\xbb\xbf﻿";

### Steps to Reproduce
view code:  src/shell.c.in: 9475 line
Use  VIM to open or other editor. do not use notepad.exe or chrome... that will filter these unseen char

you will see the line:
static const char *zBomUtf8 = "\xef\xbb\xbf﻿<feff>";

compiler will raise error for "<feff>"

SQLCipher version:
master branch
4.5.6 and release source.zip

**Comment by sjlombardo** [comment]
Hello @liuyug - I believe that character, U+FEFF (zero width no breaking space), is present deliberately as part of the BOM variable used by the SQLite shell. It is present in the upstream SQLite sources as well, and it should not interfere with compilation. We have successfully built the shell with a pretty wide variety of compilers and have not experienced any errors or problems.

Because this code in question originates in SQLite and was not modified by SQLCipher, we don't anticipate making any changes to this repo. If you continue to experience problems and would like to proceed further, you should:

1. Reproduce the issue with standard SQLite (completely excluding SQLCipher)
2. Thoroughly document the errors, including what compiler, and options (build flags) you are using
3. Submit all the details of the issue to the SQLite Forum as an issue with SQLite.

If the maintainers of SQLite make adjustments to the code in question, they would be brought down into SQLCipher at a later date once published as part of an official release.
