### ISSUE TITLE
Usage of HMAC inside the code base

### ISSUE THREAD

**Issue by Trafo** [sqlcipher/sqlcipher#515]
I would like to add a more modern encryption algorithm. For that I would like to use AES-GCM, XChaCha20, or others, which already have a MAC included in the encryption pattern.

My naive approach would be, that I just implement an empty HMAC function to the provider because it will not be needed anymore in case I use the more modern algorithm. But is the implementation using the HMAC at other places? For example, I realized it is used in sqlcipher_codec_ctx_integrity_check, without checking before if HMAC calculation is disabled. Are there other places, or I am good to go, to just ignore HMAC because MAC is included already inside the encryption and decryption algorithm?

**Comment by sjlombardo** [comment]
The required changes would likely be much more involved than that. Typically authenticated ciphers still produce a tag / mac as part of the encryption process in addition to the ciphertext. You would still need to store that (i.e. instead of the HMAC), and then be able to retrieve it and feed it back for decryption. Its possible to do that, but it would likely require changes outside of SQLCipher's "provider" interface that would not be trivial. 

Since we only use Github issues for tracking defects, I'm going to close this for now. If you have other questions related to this, the forum would be a better place to post.
