### ISSUE TITLE
Build Failed:  'openssl.cypto.h' file not found   

### ISSUE THREAD

**Issue by ossorry** [sqlcipher/sqlcipher#519]
### Expected Behavior
 I'm doing the source integration through Git  in iOS project（https://www.zetetic.net/sqlcipher/ios-tutorial/#option-1-source-integration）, but  cannot get the right result.

 There's a similar question with this issue 'openssl/rand.h' file not found #146.  
A answer in this issue  say，use  ./configure --enable-tempstore=yes --with-crypto-lib=commoncrypto CFLAGS="-DSQLITE_HAS_CODEC -DSQLITE_TEMP_STORE=2" ，but not work for me.

Do I need add the generated "splite3.c" to tartget's compile Sources? If needed ,  there still the error message "Build Failed:  'openssl.cypto.h' file not found".
if remove the .c file from compile Sources, the compilation process is fine，but sqlite3_key method always return "21". the encyption is not work correctly.

 I need help!
wish your answers.

SQLCipher version:
from GItHub
*Note:* If you are not posting a specific issue for the SQLCipher library, please consider posting your question to the SQLCipher [discuss site](https://discuss.zetetic.net/c/sqlcipher).  Thanks!

**Comment by R4N** [comment]
We see that your cross posted the same question to the [SQLCipher discussion forum](https://discuss.zetetic.net/c/sqlcipher/5) which is the appropriate place for a questions like this. We reserve GitHub issues for reporting defects/bugs in the SQLCipher library itself rather than integration issues. I'll go ahead and close this issue.
