### ISSUE TITLE
Potential Memory leak in ext/recover/sqlite3recover.c

### ISSUE THREAD

**Issue by icy17** [sqlcipher/sqlcipher#523]
Potential memory leak in [sqlite3recover.c](https://github.com/sqlcipher/sqlcipher/blob/master/ext/recover/sqlite3recover.c#L911) line 85. Calling sqlite3_open() without calling sqllite3_close() to free the memory will cause a memory leak.

![image](https://github.com/user-attachments/assets/1ffe52b1-ccd0-4cd5-80af-dfa93ea670f3)

**Comment by sjlombardo** [comment]
Hello @icy17 - It looks like this issue is rooted in the upstream SQLite project, i.e. the code originated in SQLite and was not modified by SQLCipher. Therefore it would be better to be reported to SQLite instead. This usually involves identifying / reproducing the issue with standard SQLite (completely excluding SQLCipher), documenting the issue, and then submitting a summary and/or patch to the SQLite maintainers. If and when appropriate changes are applied to upstream SQLite, the SQLCipher project would then incorporate those fixes as part of our standard release workflow.
