### ISSUE TITLE
unable to encrypt and decrypt database using SQLCipher iphone

### ISSUE THREAD

**Issue by Praskandan** [sqlcipher/sqlcipher#59]
when i encrypt existing database it gets encrypt but size is smaller than original is it right and i am also not able to decrypt it again.

**Comment by neaGaze** [comment]
Praskandan, will you please tell me how you decrypt the db?

**Comment by sharmasneha** [comment]
Hi Praskandan,  I have successfully integrated SQLCipher library. For encrypting existing sqlite Database, I have used the above code which you have mentioned. When i run this code, it is getting crashed on int err = sqlite3_key(database, key, strlen(key));. It is giving me exc_bad_access error.Could you pls help me on this. I am using Xcode ver6.3.2.

Thanks is advance

**Comment by sjlombardo** [comment]
@sharmasneha if you have a new problem it would be best to create a new issue, rather than adding a comment on an already closed issue. 

The issue you are experiencing is likely caused by including a header that is not matched to the actual library you are linking. Please double check that you are following the tutorial here exactly http://sqlcipher.net/ios-tutorial/ and ensure that you have properly set the linking options to link SQLCipher, and the includes to locate sqlcipher's header. If you are using the standard sqlite libs or headers it can result in a bad access error.
